/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package evhotel21;

/**
 *
 * @author 63997
 */
public class EnterPage extends javax.swing.JFrame {

    /**
     * Creates new form EnterPage
     */
    public EnterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 150, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("EV-HOTEL FINDER");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 420, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("WELCOME");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 240, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("EV-HOTEL FINDER ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel4.setText("We find the best hotel for you ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        jLabel5.setText("__________________________________");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("_______");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("/\\");
            jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 90, -1));

            jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 95)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(0, 255, 0));
            jLabel9.setText("E");
            jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

            jLabel11.setBackground(new java.awt.Color(255, 0, 51));
            jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
            jLabel11.setForeground(new java.awt.Color(255, 0, 51));
            jLabel11.setText("/\\");
                jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, -1));

                jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 90)); // NOI18N
                jLabel13.setForeground(new java.awt.Color(255, 255, 0));
                jLabel13.setText("__");
                jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 90, 110));

                jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 90)); // NOI18N
                jLabel14.setForeground(new java.awt.Color(255, 255, 0));
                jLabel14.setText("|");
                jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 60, 70));

                jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 90)); // NOI18N
                jLabel15.setForeground(new java.awt.Color(255, 0, 51));
                jLabel15.setText("|");
                jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 50, 90));

                jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
                jLabel16.setForeground(new java.awt.Color(0, 204, 255));
                jLabel16.setText("/\\");
                    jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, -1));

                    jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 90)); // NOI18N
                    jLabel17.setForeground(new java.awt.Color(255, 0, 51));
                    jLabel17.setText("|");
                    jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 60, 120));

                    jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 31)); // NOI18N
                    jLabel19.setForeground(new java.awt.Color(0, 204, 255));
                    jLabel19.setText("O");
                    jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

                    jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 31)); // NOI18N
                    jLabel20.setForeground(new java.awt.Color(255, 255, 0));
                    jLabel20.setText("O");
                    jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

                    jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 31)); // NOI18N
                    jLabel21.setForeground(new java.awt.Color(255, 0, 0));
                    jLabel21.setText("O");
                    jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

                    jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 90)); // NOI18N
                    jLabel18.setForeground(new java.awt.Color(0, 204, 255));
                    jLabel18.setText("__");
                    jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 110));

                    jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 90)); // NOI18N
                    jLabel22.setForeground(new java.awt.Color(255, 0, 51));
                    jLabel22.setText("__");
                    jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 80, 110));

                    jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 90)); // NOI18N
                    jLabel23.setForeground(new java.awt.Color(0, 204, 255));
                    jLabel23.setText("|");
                    jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, 120));

                    jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 200)); // NOI18N
                    jLabel25.setForeground(new java.awt.Color(0, 204, 255));
                    jLabel25.setText("|");
                    jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 60, 120));

                    jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 200)); // NOI18N
                    jLabel26.setForeground(new java.awt.Color(51, 255, 0));
                    jLabel26.setText("|");
                    jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 50, 60));

                    jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 200)); // NOI18N
                    jLabel27.setForeground(new java.awt.Color(255, 0, 51));
                    jLabel27.setText("|");
                    jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 50, 80));

                    jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 200)); // NOI18N
                    jLabel28.setForeground(new java.awt.Color(255, 255, 0));
                    jLabel28.setText("|");
                    jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 50, 100));

                    jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
                    jLabel10.setForeground(new java.awt.Color(0, 204, 255));
                    jLabel10.setText("O");
                    jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

                    jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
                    jLabel12.setForeground(new java.awt.Color(153, 255, 0));
                    jLabel12.setText("O");
                    jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

                    jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
                    jLabel24.setForeground(new java.awt.Color(255, 0, 0));
                    jLabel24.setText("O");
                    jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

                    jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
                    jLabel29.setForeground(new java.awt.Color(255, 255, 0));
                    jLabel29.setText("O");
                    jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

                    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 770, 330));

                    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel8.setText("evHotel@gmail.com");
                    jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                    );
                    layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    );

                    pack();
                    setLocationRelativeTo(null);
                }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        First info =new First ();
        info.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
